[package]
name = "helix-event"
version = "0.6.0"
authors = ["Blaž Hrastnik <blaz@mxxn.io>"]
edition = "2021"
license = "MPL-2.0"
categories = ["editor"]
repository = "https://github.com/helix-editor/helix"
homepage = "https://helix-editor.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.3"
hashbrown = "0.13.2"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "time", "sync", "parking_lot", "macros"] }
# the event registry is essentially read only but must be an rwlock so we can
# setup new events on intalization, hardware-lock-elision hugnly benefits this case
# as is essentially makes the lock entirely free as long as there is no writes 
parking_lot = { version = "0.12", features = ["hardware-lock-elision"] }
once_cell = "1.18"

anyhow = "1"
log = "0.4"
futures-executor = "0.3.28"

[features]
integration_test = []
